server:
  port: 8081
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/bank
    username: root
    password: root
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: root
  kafka:
    bootstrap-servers: localhost:9092
    bank-to-history-topic-name: bank-to-history-service
    history-to-bank-topic-name: history-to-bank-service
    partitions-amount: 1
    group-id: history-service
    producer-id: bank-service


jwt:
  signature-algorithm: HS512
  access-expiration-time-ms: 3m
  refresh-expiration-time-ms: 2h

logical-card-status:
  statuses:
    100: Запрос на изготовление отправлен
    200: Изготовлена
    300: Отправлена в отделение
    400: Находится в отделении банка
    430: Выдана клиенту
  undefined: Статус карты неизвестен